const galleryItems = [
  "gallery17.png",
  "gallery16.png",
  "gallery15.png",
  "gallery14.png",
  "gallery13.png",
  "gallery12.png",
  "gallery11.png",
  "gallery10.png",
  "gallery09.png",
  "gallery08.png",
  "gallery07.png",
  "gallery06.png",
  "gallery05.png",
  "gallery04.png",
  "gallery03.png",
  "gallery02.png",
  "gallery01.png"
];
